from legal_ai_app.rag.user_document_rag import UserDocumentRAG
from legal_ai_app.rag.legal_rag import LegalRAG
from legal_ai_app.rag.reranker import Reranker


class HybridRetriever:

    def __init__(self):

        self.user_rag = UserDocumentRAG()
        self.legal_rag = LegalRAG()
        self.reranker = Reranker()

    def retrieve(
        self,
        question: str,
        category: str | None = None,
        retrieval_queries: list[str] | None = None,
        user_k: int = 5,
        legal_k: int = 5,
        top_k: int = 5,
    ):

        # Use the original question plus
        # queries generated by the issue analyzer.
        queries = [question]

        if retrieval_queries:
            queries.extend(retrieval_queries)

        user_documents = []
        legal_documents = []

        # Search every query.
        for query in queries:

            user_results = self.user_rag.retrieve(
                query,
                user_k,
            )

            legal_results = self.legal_rag.retrieve(
                query,
                category=category,
                k=legal_k,
            )

            user_documents.extend(
                user_results
            )

            legal_documents.extend(
                legal_results
            )

        # Mark retrieval source.
        for document in user_documents:

            document.metadata[
                "retrieval_source"
            ] = "user_document"

        for document in legal_documents:

            document.metadata[
                "retrieval_source"
            ] = "legal_knowledge"

        # Combine results.
        documents = (
            user_documents
            + legal_documents
        )

        # Remove duplicate chunks.
        unique_documents = []
        seen = set()

        for document in documents:

            content = document.page_content.strip()

            key = (
                document.metadata.get(
                    "retrieval_source"
                ),
                content,
            )

            if key not in seen:

                seen.add(key)

                unique_documents.append(
                    document
                )

        # Rerank all retrieved candidates.
        return self.reranker.rerank(
            question=question,
            documents=unique_documents,
            top_k=top_k,
        )